## S&P 500 Galaxy

Use this utility to update the returns and std_dev fields within investment-options.csv

Globals

In [1]:
# Set refresh_timeseries=True to download timeseries.  Otherwise /symbol-cache is used.
refresh_timeseries = False
throttle_limit=100
wait_time=30

In [2]:
%%javascript
IPython.OutputArea.prototype._should_scroll = function(lines) {
    return false;
}

In [3]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

import brownbear as bb

# format price data
pd.options.display.float_format = '{:0.2f}'.format

In [4]:
# read in sp500.csv
sp500 = pd.read_csv('sp500.csv')
sp500.drop(columns=['Headquarters Location', 'Date added','CIK', 'Founded'], inplace=True)
sp500.rename(columns={'Security':'Description',
                      'GICS Sector':'Asset Class'}, inplace=True)
sp500.set_index("Symbol", inplace=True)
sp500

,Description,Asset Class,GICS Sub-Industry
Symbol,,,
MMM,3M,Industrials,Industrial Conglomerates
AOS,A. O. Smith,Industrials,Building Products
ABT,Abbott Laboratories,Health Care,Health Care Equipment
ABBV,AbbVie,Health Care,Biotechnology
ACN,Accenture,Information Technology,IT Consulting & Other Services
...,...,...,...
XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components
YUM,Yum! Brands,Consumer Discretionary,Restaurants
ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments
ZBH,Zimmer Biomet,Health Care,Health Care Equipment
ZTS,Zoetis,Health Care,Pharmaceuticals

In [5]:
# read in gics-2-asset-class.csv
gics2asset_class = pd.read_csv('gics-2-asset-class.csv', skip_blank_lines=True, comment='#')
gics2asset_class.set_index("GICS", inplace=True)
gics2asset_class = gics2asset_class['Asset Class'].to_dict()
gics2asset_class

{'Energy': 'US Stocks:Energy',
 'Materials': 'US Stocks:Materials',
 'Industrials': 'US Stocks:Industrials',
 'Consumer Discretionary': 'US Stocks:Consumer Discretionary',
 'Consumer Staples': 'US Stocks:Consumer Staples',
 'Health Care': 'US Stocks:Healthcare',
 'Financials': 'US Stocks:Financials',
 'Information Technology': 'US Stocks:Technology',
 'Communication Services': 'US Stocks:Communication Services',
 'Utilities': 'US Stocks:Utilities',
 'Real Estate': 'US Stocks:Real Estate'}

In [6]:
# Map sp500 GICS sectors to brownbear defined asset classes.
def _asset_class(row):
    return gics2asset_class[row['Asset Class']]

sp500['Asset Class'] = sp500.apply(_asset_class, axis=1)

# Yahoo finance uses '-' where '.' is used in symbol names.
sp500.index = sp500.index.str.replace('.', '-', regex=False)
sp500

,Description,Asset Class,GICS Sub-Industry
Symbol,,,
MMM,3M,US Stocks:Industrials,Industrial Conglomerates
AOS,A. O. Smith,US Stocks:Industrials,Building Products
ABT,Abbott Laboratories,US Stocks:Healthcare,Health Care Equipment
ABBV,AbbVie,US Stocks:Healthcare,Biotechnology
ACN,Accenture,US Stocks:Technology,IT Consulting & Other Services
...,...,...,...
XYL,Xylem Inc.,US Stocks:Industrials,Industrial Machinery & Supplies & Components
YUM,Yum! Brands,US Stocks:Consumer Discretionary,Restaurants
ZBRA,Zebra Technologies,US Stocks:Technology,Electronic Equipment & Instruments
ZBH,Zimmer Biomet,US Stocks:Healthcare,Health Care Equipment
ZTS,Zoetis,US Stocks:Healthcare,Pharmaceuticals

In [7]:
# Remove symbols without enough data
sp500.drop('FDXF', inplace=True)

In [8]:
# Make symbols list.
symbols = list(sp500.index)

In [9]:
# Get the timeseries for the symbols and compile into a single csv.
bb.fetch_timeseries(symbols, refresh=refresh_timeseries, throttle_limit=throttle_limit, wait_time=wait_time)
bb.compile_timeseries(symbols)

MMM AOS

ABT

ABBV

ACN

ADBE AMD AES

AFL

A

APD

ABNB AKAM

ALB

ARE

ALGN

ALLE

LNT

ALL

GOOGL GOOG MO

AMZN AMCR

AEE

AEP AXP AIG

AMT

AWK

AMP

AME

AMGN APH

ADI AON

APA

APO

AAPL AMAT APP APTV

ACGL

ADM

ARES

ANET

AJG

AIZ

T

ATO

ADSK ADP AZO

AVB

AVY

AXON BKR BALL

BAC

BAX

BDX

BRK-B

BBY

TECH

BIIB

BLK

BX

XYZ

BNY

BA BKNG BSX

BMY

AVGO BR

BRO

BF-B

BLDR

BG

BXP

CHRW

CDNS CPT

CPB

COF

CAH

CCL

CARR

CVNA

CASY

CAT CBOE

CBRE

CDW

COR

CNC

CNP

CF

CRL

SCHW

Throttle limit reached. Waiting for 30 seconds...

CHTR CVX CMG

CB

CHD

CIEN

CI

CINF

CTAS CSCO C

CFG

CLX

CME

CMS

KO CTSH COHR

COIN

CL

CMCSA FIX

CAG

COP

ED

STZ

CEG COO

CPRT GLW

CPAY

CTVA

CSGP

COST CRH

CRWD CCI

CSX CMI

CVS

DHR

DRI

DDOG DVA

DECK

DE

DELL

DAL

DVN

DXCM FANG DLR

DG

DLTR

D

DPZ

DASH DOV

DOW

DHI

DTE

DUK

DD

ETN

EBAY

SATS

ECL

EIX

EW

EA ELV

EME

EMR

ETR

EOG

EQT

EFX

EQIX

EQR

ERIE

ESS

EL

EG

EVRG

ES

EXC EXE

EXPE

EXPD

EXR

XOM

FFIV

FDS

FICO

FAST FRT

FDX

FIS

FITB

FSLR

Throttle limit reached. Waiting for 30 seconds...

FE

FISV

F

FTNT FTV

FOXA

FOX

BEN

FCX

GRMN

IT

GE

GEHC GEV

GEN

GNRC

GD

GIS

GM

GPC

GILD GPN

GL

GDDY

GS HAL

HIG

HAS

HCA

DOC

HSIC

HSY

HPE

HLT

HD HON HRL

HST

HWM

HPQ

HUBB

HUM

HBAN

HII

IBM IEX

IDXX ITW

INCY

IR

PODD

INTC IBKR

ICE

IFF

IP

INTU ISRG IVZ

INVH

IQV

IRM

JBHT

JBL

JKHY

J

JNJ JCI

JPM KVUE

KDP KEY

KEYS

KMB

KIM

KMI

KKR

KLAC KHC KR

LHX

LH

LRCX LVS

LDOS

LEN

LII

LLY

LIN LYV

LMT

L

LOW

LULU

LITE LYB

MTB

MPC

MAR MRSH

Throttle limit reached. Waiting for 30 seconds...

MLM

MAS

MA

MKC

MCD MCK

MDT

MRK META MET

MTD

MGM

MCHP MU MSFT MAA

MRNA

TAP

MDLZ MPWR MNST MCO

MS

MOS

MSI

MSCI

NDAQ

NTAP

NFLX NEM

NWSA

NWS

NEE

NKE NI

NDSN

NSC

NTRS

NOC

NCLH

NRG

NUE

NVDA NVR

NXPI ORLY OXY

ODFL OMC

ON

OKE

ORCL

OTIS

PCAR PKG

PLTR PANW PSKY

PH

PAYX PYPL PNR

PEP PFE

PCG

PM PSX

PNW

PNC

POOL

PPG

PPL

PFG

PG PGR

PLD

PRU

PEG

PTC

PSA

PHM

PWR

QCOM DGX

Q RL

RJF

RTX

O

REG

REGN RF RSG

RMD

RVTY

HOOD

ROK

ROL

ROP ROST
Throttle limit reached. Waiting for 30 seconds...

RCL

SPGI

CRM SNDK SBAC

SLB

STX SRE

NOW

SHW SPG

SWKS

SJM

SW

SNA

SOLV SO

LUV

SWK

SBUX STT

STLD

STE

SYK

SMCI

SYF

SNPS SYY

TMUS TROW

TTWO TPR

TRGP

TGT

TEL

TDY

TER

TSLA TXN TPL

TXT

TMO

TJX

TKO

TTD

TSCO

TT

TDG TRV TRMB

TFC

TYL

TSN

USB

UBER

UDR

ULTA

UNP

UAL

UPS

URI

UNH UHS

VLO

VEEV

VTR

VLTO

VRSN

VRSK VZ VRTX VRT

VTRS

VICI

V VST

VMC WRB

GWW

WAB

WMT DIS WBD WM

WAT

WEC

WFC

WELL

WST

WDC WY

WSM

WMB

WTW

WDAY WYNN

XEL XYL

YUM

ZBRA

Throttle limit reached. Waiting for 30 seconds...

ZBH

ZTS

In [10]:
# Read symbols timeseries into a dataframe.
df = pd.read_csv('symbols-timeseries.csv', skip_blank_lines=True, comment='#')
df.set_index("Date", inplace=True)
df = df[:]
df.tail()[['NVDA', 'WST', 'ADBE', 'NOW', 'AMD', 'PYPL', 'AAPL', 'MSFT', 'DHR', 'TMO', 'AMZN', 'DXCM', 'ODFL', 'REGN', 'ROL', 'FDX', 'TMUS', 'CDNS', 'CRM', 'MSCI']]

,NVDA,WST,ADBE,NOW,AMD,PYPL,AAPL,MSFT,DHR,TMO,AMZN,DXCM,ODFL,REGN,ROL,FDX,TMUS,CDNS,CRM,MSCI
Date,,,,,,,,,,,,,,,,,,,,
2026-04-23,199.41,309.47,238.98,84.78,305.33,49.59,273.18,414.85,178.57,466.23,255.08,62.70,222.50,764.88,56.80,316.43,193.02,314.33,172.85,595.86
2026-04-24,208.03,305.93,245.44,90.17,347.81,50.31,270.81,423.70,177.25,469.24,263.99,61.57,219.70,750.45,56.41,312.63,188.78,332.89,177.70,590.56
2026-04-27,216.36,301.97,239.31,90.45,334.63,49.61,267.36,423.90,180.62,467.57,261.12,61.41,220.25,743.33,55.78,312.56,181.76,336.54,179.72,588.89
2026-04-28,212.92,291.91,243.20,90.49,323.21,49.48,270.46,428.32,178.98,469.75,259.70,59.32,221.49,730.68,55.55,314.43,185.71,325.31,180.85,592.64
2026-04-29,209.01,295.36,243.57,88.89,337.11,50.77,269.92,423.54,178.80,465.79,263.04,57.56,209.08,685.34,55.14,313.13,197.10,329.95,180.75,595.98

In [11]:
# Calculate Annual Returns.
annual_returns = bb.annualized_returns(df, timeperiod='daily', years=1)
annual_returns

MMM      6.23
AOS      0.31
ABT    -28.05
ABBV     9.46
ACN    -37.70
        ...
XYL      0.77
YUM     10.26
ZBRA   -11.48
ZBH    -20.49
ZTS    -24.73
Length: 502, dtype: float64

In [12]:
# Calculate 3 month, 6 months, 1 year, 1-1 year, 3 year, and 5 year annualized returns.
annual_returns_3mo = bb.annualized_returns(df, timeperiod='daily', years=3/12)
annual_returns_6mo = bb.annualized_returns(df, timeperiod='daily', years=6/12)
annual_returns_1yr = bb.annualized_returns(df, timeperiod='daily', years=1)
annual_returns_1_1yr = bb.annualized_returns(df, timeperiod='daily', years=1, offset=1)
annual_returns_3yr = bb.annualized_returns(df, timeperiod='daily', years=3)
annual_returns_5yr = bb.annualized_returns(df, timeperiod='daily', years=5)

In [13]:
# Calculate 20 day annualized volatility.
daily_returns = df.pct_change(fill_method=None)
years = bb.TRADING_DAYS_PER_MONTH / bb.TRADING_DAYS_PER_YEAR
vola = bb.annualized_standard_deviation(daily_returns, timeperiod='daily', years=years)

In [14]:
# Calculate 20 day annualized downside volatility.
ds_vola = bb.annualized_standard_deviation(daily_returns, timeperiod='daily', years=years, downside=True)

In [15]:
# Resample df on a monthly basis.
df.index = pd.to_datetime(df.index)
monthly = df.resample('ME').ffill()

In [16]:
# Calculate monthly returns.
monthly_returns = monthly.pct_change()

In [17]:
# Calculate 1 year, 3 year, and 5 year annualized standard deviation.
std_dev_1yr = bb.annualized_standard_deviation(monthly_returns, timeperiod='monthly', years=1)
std_dev_3yr = bb.annualized_standard_deviation(monthly_returns, timeperiod='monthly', years=3)
std_dev_5yr = bb.annualized_standard_deviation(monthly_returns, timeperiod='monthly', years=5)

In [18]:
# Read investment-options-header.csv
lines = []
with open('investment-options-in.csv', 'r') as f:
    lines = [line.strip() for line in f]

In [19]:
# For each symbol, write out the 1 Yr, 3 Yr, 5 Yr, and std dev.
out = lines.copy()

# This is still slow (2.53 s).
for i, (index, row) in enumerate(sp500.iterrows()):

    symbol = index
    description = row['Description']
    asset_class = row['Asset Class']

    ret_3mo = annual_returns_3mo[symbol]
    ret_6mo = annual_returns_6mo[symbol]
    ret_1yr = annual_returns_1yr[symbol]
    ret_1_1yr = annual_returns_1_1yr[symbol]
    ret_3yr = annual_returns_3yr[symbol]
    ret_5yr = annual_returns_5yr[symbol]
    
    if np.isnan(ret_3yr): ret_3yr = ret_1yr
    if np.isnan(ret_5yr): ret_5yr = ret_3yr

    _vola = vola[symbol]*100
    _ds_vola = ds_vola[symbol]*100
    sd_1yr = std_dev_1yr[symbol]*100
    sd_3yr = std_dev_3yr[symbol]*100
    sd_5yr = std_dev_5yr[symbol]*100

    out.append(
        f'"{symbol}","{description}","{asset_class}",'
        f'"{ret_3mo:0.2f}","{ret_6mo:0.2f}","{ret_1yr:0.2f}","{ret_1_1yr:0.2f}","{ret_3yr:0.2f}",'
        f'"{ret_5yr:0.2f}","{_vola:0.2f}","{_ds_vola:0.2f}","{sd_1yr:0.2f}","{sd_3yr:0.2f}","{sd_5yr:0.2f}"'
    )

In [20]:
# Write out asset-classes.csv
with open('investment-options.csv', 'w') as f:
    for line in out:
        f.write(line + '\n')