## S&P 600 Galaxy

Use this utlity to update the returns and std_dev fields within investment-options.csv

Globals

In [1]:
# Set refresh_timeseries=True to download timeseries.  Otherwise /symbol-cache is used.
refresh_timeseries = False
throttle_limit=100
wait_time=30

In [2]:
%%javascript
IPython.OutputArea.prototype._should_scroll = function(lines) {
    return false;
}

In [3]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

import brownbear as bb

# Format price data.
pd.options.display.float_format = '{:0.2f}'.format

In [4]:
# Read in sp600.csv
sp600 = pd.read_csv('sp600.csv')
sp600.drop(columns=['SEC filings', 'CIK'], inplace=True)
sp600.rename(columns={'Security':'Description',
                      'GICS Sector':'Asset Class',
                      'GICS Sub-Industry': 'GICS Sub Industry'}, inplace=True)
sp600.set_index("Symbol", inplace=True)
sp600

,Description,Asset Class,GICS Sub Industry,Headquarters Location
Symbol,,,,
AAMI,Acadian Asset Management Inc.,Financials,Asset Management & Custody Banks,"Boston, Massachusetts"
AAP,"Advance Auto Parts, Inc.",Consumer Discretionary,Automotive Retail,"Raleigh, North Carolina"
AAT,American Assets Trust,Real Estate,Diversified REITs,"San Diego, California"
ABCB,Ameris Bancorp,Financials,Regional Banks,"Atlanta, Georgia"
ABG,Asbury Automotive Group,Consumer Discretionary,Automotive Retail,"Duluth, Georgia"
...,...,...,...,...
XPEL,"XPEL, Inc.",Consumer Discretionary,Automotive Parts & Equipment,"San Antonio, Texas"
YELP,"Yelp, Inc.",Communication Services,Interactive Media & Services,"San Francisco, California"
YOU,"Clear Secure, Inc.",Information Technology,Application Software,"New York City, New York"
ZD,Ziff Davis,Communication Services,Advertising,"New York City, New York"
ZWS,Zurn Elkay Water Solutions Corp.,Industrials,Industrial Machinery & Supplies & Components,"Milwaukee, Wisconsin"

In [5]:
# Read in gics-2-asset-class.csv
gics2asset_class = pd.read_csv('gics-2-asset-class.csv', skip_blank_lines=True, comment='#')
gics2asset_class.set_index("GICS", inplace=True)
gics2asset_class = gics2asset_class['Asset Class'].to_dict()
gics2asset_class

{'Energy': 'US Stocks:Energy',
 'Materials': 'US Stocks:Materials',
 'Industrials': 'US Stocks:Industrials',
 'Consumer Discretionary': 'US Stocks:Consumer Discretionary',
 'Consumer Staples': 'US Stocks:Consumer Staples',
 'Health Care': 'US Stocks:Healthcare',
 'Financials': 'US Stocks:Financials',
 'Information Technology': 'US Stocks:Technology',
 'Communication Services': 'US Stocks:Communication Services',
 'Utilities': 'US Stocks:Utilities',
 'Real Estate': 'US Stocks:Real Estate'}

In [6]:
# Map sp600 GICS sectors to brownbear defined asset classes.
def _asset_class(row):
    return gics2asset_class[row['Asset Class']]

sp600['Asset Class'] = sp600.apply(_asset_class, axis=1)

# Yahoo finance uses '-' where '.' is used in symbol names.
sp600.index = sp600.index.str.replace('.', '-', regex=False)
sp600

,Description,Asset Class,GICS Sub Industry,Headquarters Location
Symbol,,,,
AAMI,Acadian Asset Management Inc.,US Stocks:Financials,Asset Management & Custody Banks,"Boston, Massachusetts"
AAP,"Advance Auto Parts, Inc.",US Stocks:Consumer Discretionary,Automotive Retail,"Raleigh, North Carolina"
AAT,American Assets Trust,US Stocks:Real Estate,Diversified REITs,"San Diego, California"
ABCB,Ameris Bancorp,US Stocks:Financials,Regional Banks,"Atlanta, Georgia"
ABG,Asbury Automotive Group,US Stocks:Consumer Discretionary,Automotive Retail,"Duluth, Georgia"
...,...,...,...,...
XPEL,"XPEL, Inc.",US Stocks:Consumer Discretionary,Automotive Parts & Equipment,"San Antonio, Texas"
YELP,"Yelp, Inc.",US Stocks:Communication Services,Interactive Media & Services,"San Francisco, California"
YOU,"Clear Secure, Inc.",US Stocks:Technology,Application Software,"New York City, New York"
ZD,Ziff Davis,US Stocks:Communication Services,Advertising,"New York City, New York"
ZWS,Zurn Elkay Water Solutions Corp.,US Stocks:Industrials,Industrial Machinery & Supplies & Components,"Milwaukee, Wisconsin"

In [7]:
# Drop invalid symbols.
sp600.drop(['VSNT'], inplace=True)

In [8]:
# Make symbols list.
symbols = list(sp600.index)

In [9]:
# Get the timeseries for the symbols and compile into a single csv.
bb.fetch_timeseries(symbols, refresh=refresh_timeseries, throttle_limit=throttle_limit, wait_time=wait_time)
bb.compile_timeseries(symbols)

AAMI

AAP

AAT

ABCB

ABG

ABM

ABR

ACA

ACAD

ACHC

ACIW

ACLS

ACMR

ACT

ADAM

ADEA

ADMA

ADNT

ADT

ADUS

AEO

AESI

AGNT

AGO

AGX

AGYS

AHCO

AIN

AIR

AKR

ALG

ALGT

ALHC

ALKS

ALRM

AMN

AMPH

AMR

AMRX

AMSF

AMTM

ANDE

ANIP

AORT

AOSL

APAM

APLE

APOG

ARCB

ARI

ARLO

AROC

ARR

ASO

ASTE

ASTH

ATEN

ATMU

AUB

AVA

AVNS

AWI

AWR

AX

AZTA

AZZ

BANC

BANF

BANR

BBT

BCC

BCPC

BFAM

BFH

BFS

BGC

BHE

BJRI

BKE

BKU

BL

BLFS

BMI

BNL

BOH

BOOT

BOX

BRC

BTSG

BTU

BXMT

CABO

CAKE

CALM

CALX

CALY

CARG

CASH

CATY

CBRL

Throttle limit reached. Waiting for 30 seconds...

CBU

CC

CCOI

CCS

CE

CENT

CENTA

CENX

CERT

CFFN

CHCO

CHEF

CLB

CLSK

CNK

CNMD

CNR

CNS

CNXN

COCO

COHU

COLL

CON

CORT

CPF

CPK

CPRX

CRC

CRGY

CRI

CRK

CRSR

CRVL

CSR

CSW

CTKB

CTS

CUBI

CURB

CVBF

CVCO

CVI

CVSA

CWEN

CWEN-A

CWK

CWST

CWT

CXM

CXW

CZR

DAN

DAVE

DBD

DCH

DCOM

DEA

DEI

DFH

DFIN

DGII

DIOD

DLX

DNOW

DORM

DRH

DV

DXC

DXPE

EAT

ECG ECPG

EFC

EFOR

EGBN

EIG

EMBC

EMN

ENOV

ENPH

ENR

ENVA

EPAC

EPAM

EPC

EPRT

ESE

ESI

ETD

ETSY

EVTC

EXTR

EYE

EZPW

FBK

FBNC

FBP

FBRT

FCF

FCPT

Throttle limit reached. Waiting for 30 seconds...

FDP

FELE

FFBC

FG

FHB

FIBK

FIZZ

FLO

FMC

FORM

FOXF

FRPT

FSS

FTDR

FTRE

FUL

FULT

FUN

FWRD

GBX

GDYN

GEO

GFF

GIII

GKOS

GNL

GNW

GO

GOGO

GOLF

GPI

GRBK

GSHD

GTES

GTM

GTY

GVA

HAFC

HASI

HAYW

HCC

HCI

HCSG

HE

HFWA

HIW

HLIT

HLX

HMN

HNI

HOPE

HP

HRMY

HSTM

HTH

HTLD

HTO

HTZ

HUBG

HWKN

HZO

IART

IBP

ICHR

ICUI

IIIN

IIPR

INDB

INDV

INSP

INSW

INVA

INVX

IOSP

IPAR

IRDM

ITGR

ITRI

JBGS

JBLU

JBSS

JBTM

JJSF

JOE

JXN

KAI

KALU

OPLN

KFY

KGS

KLIC

KMPR

KMT

KMX

KN

KNTK

KOP

KRYS

KSS

KTB

Throttle limit reached. Waiting for 30 seconds...

KW

KWR

LAUR

LBRT

LCII

LEG

LFST

LGIH

LIF

LGND

LKFN

LKQ

LMAT

LNC

LNN

LPG

LQDT

LRN

LTC

LTH

LUMN

LW

LXP

LYFT

LZ

LZB

MAC

MAN

MARA

MATW

MATX

MBC

MBIN

MC

MCRI

MCY

MD

MDU

MGEE

MGY

MHK

MHO

MIR

MKTX

MLKN

MMI

MMSI

MNRO

MOH

MPT MRCY

MRP MRTN

MSEX

MSGS

MTCH

MTH

MTRN

MTUS

MTX

MWA

MXL

MYRG

NABL

NATL

NAVI

NBHC

NBTB

NE

NEO

NEOG

NGVT

NHC

NMIH

NOG

NPK

NPO

NSIT

NSP

NSSC

NTCT

NWBI

NWL

NWN

NX

NXRT

OFG

OGN

OI

OII

OMCL

OSIS

OSW

OTTR

OUT

OXM

PAHC

PARR

PAYC

PAYO

Throttle limit reached. Waiting for 30 seconds...

PATK

PBH

PBI

PCRX

PDFS

PEB

PECO

PENG

PENN

PFBC

PFS

PGNY

PHIN

PI

PIPR

PJT

PLAB

PLMR

PLUS

PLXS

PMT

POWI

POWL

PPLI

PRA PRAA

PRDO

PRG

PRGO

PRGS

PRIM

PRK

PRKS

PRLB

PRSU

PRVA

PSMT

PTCT

PTEN

PTGX

PTON

PZZA

QDEL

QNST

QRVO

QTWO

RAMP

RAL

RCUS

RDN

RDNT

RELY

RES

REYN

REX

REZI

RHI

RHP

RITM

RNG

RNST

ROCK

ROG

RRR

RUN

RUSHA

RWT

RXO

SAFE

SABR

SAFT

SAH

SANM

SBCF

SBH

SBSI

SCHL

SCL

SCSC

SDGR

SEDG

SEM

SEZL

SFBS

SFNC

SHAK

SHEN

SHO

SHOO

SIG

SKT

SKY

SKYW

SLG

SLVM

SM

SMP

SMPL

SMTC

SNDR

Throttle limit reached. Waiting for 30 seconds...

SNEX

SONO

SPHR

SPNT

SPSC

SRPT

STAA

STBA

STC

STEL

STEP

STRA

SUPN

SXI

SXT

TALO

TBBK

TDC

TDS

TDW

TFIN

TFX

TGTX

THRM

TILE

TMDX

TMP

TNC

TNDM

TR

TRIP

TRMK

TRN

TRNO

TRST

TRUP

TWO

UA

UAA

UCB

UCTT

UE

UFCS

UFPT

UHT

UNF

UNFI

UNIT

UPBD

UPWK

URBN

USPH

UTI

UTL

UVV

VAC

VCEL

VCTR

VCYT

VECO

VGNT VIAV

VIR

VIRT

VITL

VRRM

VRTS

VSAT

VSEC

VSH

VSTS

VSXY

VTOL

VYX

WABC

WAFD

WAY WD

WDFC

WEN

WERN

WGO

WHD

WINA

WKC

WLY

WOR

WRLD

WS

WSC

WSFS

WSR

WT

WU

WWW

XHR

XNCR

XPEL

YELP

YOU

Throttle limit reached. Waiting for 30 seconds...

ZD

ZWS

In [10]:
# Read symbols timeseries into a dataframe.
df = pd.read_csv('symbols-timeseries.csv', skip_blank_lines=True, comment='#')
df.set_index("Date", inplace=True)
df

,AAMI,AAP,AAT,ABCB,ABG,ABM,ABR,ACA,ACAD,ACHC,...,WT,WU,WWW,XHR,XNCR,XPEL,YELP,YOU,ZD,ZWS
Date,,,,,,,,,,,,,,,,,,,,,
2019-01-02,10.46,138.41,27.81,28.79,68.12,26.98,4.59,27.52,16.65,25.86,...,5.86,10.39,27.52,13.62,35.79,NaN,34.57,NaN,59.27,10.66
2019-01-03,10.44,142.73,27.82,28.69,67.84,26.70,4.67,27.53,16.17,25.40,...,5.54,10.23,26.96,13.55,34.86,NaN,33.64,NaN,57.62,10.05
2019-01-04,10.56,139.19,28.04,29.81,68.47,27.61,4.79,28.25,17.57,26.14,...,5.69,10.36,27.54,14.04,36.58,NaN,34.56,NaN,60.02,10.45
2019-01-07,10.74,141.23,28.48,30.99,70.66,28.88,4.91,29.65,18.23,26.30,...,5.74,10.33,27.69,14.04,38.09,NaN,34.83,NaN,60.60,10.51
2019-01-08,10.55,140.25,29.07,30.92,69.83,30.17,4.99,29.42,18.54,26.99,...,5.90,10.35,28.09,14.51,38.01,NaN,35.51,NaN,60.88,10.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-04-23,66.85,58.16,20.40,84.62,202.01,40.51,7.57,120.19,22.11,27.34,...,16.88,9.04,17.68,16.09,12.45,46.84,28.32,53.60,46.97,52.63
2026-04-24,67.69,58.18,20.61,84.89,203.06,40.16,7.74,119.44,21.96,27.38,...,16.34,8.62,17.74,16.08,12.98,46.63,28.74,54.66,46.54,52.35
2026-04-27,68.09,57.87,20.88,85.12,200.03,40.11,7.84,120.44,22.30,28.15,...,16.62,9.08,17.47,16.08,13.10,46.50,29.11,54.59,48.23,52.67
2026-04-28,66.82,56.60,21.26,85.66,200.56,40.44,7.82,117.90,22.67,27.58,...,16.69,8.66,17.26,16.12,12.15,46.03,27.74,53.62,47.21,52.01
2026-04-29,65.00,55.76,20.15,84.32,201.39,39.78,7.56,116.45,22.20,28.26,...,16.16,8.70,16.91,16.07,11.62,46.61,28.01,53.18,46.76,50.76

In [11]:
# Calculate Annual Returns.
annual_returns = bb.annualized_returns(df, timeperiod='daily', years=1)
annual_returns

AAMI   142.50
AAP     74.26
AAT     15.17
ABCB    49.68
ABG    -10.27
        ...
XPEL    70.98
YELP   -21.28
YOU    116.97
ZD      51.57
ZWS     52.30
Length: 602, dtype: float64

In [12]:
# Calculate 3 month, 6 months, 1 year, 1-1 year, 3 year, and 5 year annualized returns.
annual_returns_3mo = bb.annualized_returns(df, timeperiod='daily', years=3/12)
annual_returns_6mo = bb.annualized_returns(df, timeperiod='daily', years=6/12)
annual_returns_1yr = bb.annualized_returns(df, timeperiod='daily', years=1)
annual_returns_1_1yr = bb.annualized_returns(df, timeperiod='daily', years=1, offset=1)
annual_returns_3yr = bb.annualized_returns(df, timeperiod='daily', years=3)
annual_returns_5yr = bb.annualized_returns(df, timeperiod='daily', years=5)

In [13]:
# Calculate 20 day annualized volatility.
daily_returns = df.pct_change()
years = bb.TRADING_DAYS_PER_MONTH / bb.TRADING_DAYS_PER_YEAR
vola = bb.annualized_standard_deviation(daily_returns, timeperiod='daily', years=years)

In [14]:
# Calculate 20 day annualized downside volatility.
ds_vola = bb.annualized_standard_deviation(daily_returns, timeperiod='daily', years=years, downside=True)

In [15]:
# Resample df on a monthly basis.
df.index = pd.to_datetime(df.index)
monthly = df.resample('ME').ffill()

In [16]:
# Calculate monthly returns.
monthly_returns = monthly.pct_change()

In [17]:
# Calculate 1 year, 3 year, and 5 year annualized standard deviation.
std_dev_1yr = bb.annualized_standard_deviation(monthly_returns, timeperiod='monthly', years=1)
std_dev_3yr = bb.annualized_standard_deviation(monthly_returns, timeperiod='monthly', years=3)
std_dev_5yr = bb.annualized_standard_deviation(monthly_returns, timeperiod='monthly', years=5)

In [18]:
# Read investment-options-header.csv
lines = []
with open('investment-options-in.csv', 'r') as f:
    lines = [line.strip() for line in f]

In [19]:
# For each symbol, write out the 1 Yr, 3 Yr, 5 Yr, and std dev.
out = lines.copy()

# This is still slow (2.53 s).
for i, (index, row) in enumerate(sp600.iterrows()):

    symbol = index
    description = row['Description']
    asset_class = row['Asset Class']

    ret_3mo = annual_returns_3mo[symbol]
    ret_6mo = annual_returns_6mo[symbol]
    ret_1yr = annual_returns_1yr[symbol]
    ret_1_1yr = annual_returns_1_1yr[symbol]
    ret_3yr = annual_returns_3yr[symbol]
    ret_5yr = annual_returns_5yr[symbol]
    
    if np.isnan(ret_3yr): ret_3yr = ret_1yr
    if np.isnan(ret_5yr): ret_5yr = ret_3yr

    _vola = vola[symbol]*100
    _ds_vola = ds_vola[symbol]*100
    sd_1yr = std_dev_1yr[symbol]*100
    sd_3yr = std_dev_3yr[symbol]*100
    sd_5yr = std_dev_5yr[symbol]*100

    out.append(
        f'"{symbol}","{description}","{asset_class}",'
        f'"{ret_3mo:0.2f}","{ret_6mo:0.2f}","{ret_1yr:0.2f}","{ret_1_1yr:0.2f}","{ret_3yr:0.2f}",'
        f'"{ret_5yr:0.2f}","{_vola:0.2f}","{_ds_vola:0.2f}","{sd_1yr:0.2f}","{sd_3yr:0.2f}","{sd_5yr:0.2f}"'
    )

In [20]:
# Write out asset-classes.csv
with open('investment-options.csv', 'w') as f:
    for line in out:
        f.write(line + '\n')