## Nasdaq 100 Galaxy

Use this utlity to update the returns and std_dev fields within investment-options.csv

Globals

In [1]:
# Set refresh_timeseries=True to download timeseries.  Otherwise /symbol-cache is used.
refresh_timeseries = False
throttle_limit=100
wait_time=30

In [2]:
%%javascript
IPython.OutputArea.prototype._should_scroll = function(lines) {
    return false;
}

In [3]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

import brownbear as bb

# Format price data.
pd.options.display.float_format = '{:0.2f}'.format

In [4]:
# Read in nasdaq100.csv
nasdaq100 = pd.read_csv('nasdaq100.csv')
#nasdaq100.drop(columns=['SEC filings'], inplace=True)
nasdaq100.rename(columns={'Ticker': 'Symbol',
                      'Company':'Description'}, inplace=True)
nasdaq100.set_index("Symbol", inplace=True)
nasdaq100

,Description,ICB Industry[15],ICB Subsector[15]
Symbol,,,
ADBE,Adobe Inc.,Technology,Computer Software
AMD,Advanced Micro Devices,Technology,Semiconductors
ABNB,Airbnb,Consumer Discretionary,Diversified Commercial Services
ALNY,Alnylam Pharmaceuticals,Health Care,Biotechnology
GOOGL,Alphabet Inc. (Class A),Technology,Computer Software
...,...,...,...
WBD,Warner Bros. Discovery,Consumer Discretionary,Miscellaneous Amusement & Recreation Services
WDC,Western Digital,Technology,Electronic Components
WDAY,"Workday, Inc.",Technology,EDP Services
XEL,Xcel Energy,Utilities,Power Generation
ZS,Zscaler,Technology,EDP Services

In [5]:
# Read in gics-2-asset-class.csv
gics2asset_class = pd.read_csv('gics-2-asset-class.csv', skip_blank_lines=True, comment='#')
gics2asset_class.set_index("GICS", inplace=True)
gics2asset_class = gics2asset_class['Asset Class'].to_dict()
gics2asset_class

{'Energy': 'US Stocks:Energy',
 'Materials': 'US Stocks:Materials',
 'Industrials': 'US Stocks:Industrials',
 'Consumer Discretionary': 'US Stocks:Consumer Discretionary',
 'Consumer Staples': 'US Stocks:Consumer Staples',
 'Health Care': 'US Stocks:Healthcare',
 'Financials': 'US Stocks:Financials',
 'Information Technology': 'US Stocks:Technology',
 'Communication Services': 'US Stocks:Communication Services',
 'Utilities': 'US Stocks:Utilities',
 'Real Estate': 'US Stocks:Real Estate'}

In [6]:
# Add Asset Class column.
nasdaq100['Asset Class'] = 'US Stocks'

# Yahoo finance uses '-' where '.' is used in symbol names.
nasdaq100.index = nasdaq100.index.str.replace('.', '-', regex=False)
nasdaq100

,Description,ICB Industry[15],ICB Subsector[15],Asset Class
Symbol,,,,
ADBE,Adobe Inc.,Technology,Computer Software,US Stocks
AMD,Advanced Micro Devices,Technology,Semiconductors,US Stocks
ABNB,Airbnb,Consumer Discretionary,Diversified Commercial Services,US Stocks
ALNY,Alnylam Pharmaceuticals,Health Care,Biotechnology,US Stocks
GOOGL,Alphabet Inc. (Class A),Technology,Computer Software,US Stocks
...,...,...,...,...
WBD,Warner Bros. Discovery,Consumer Discretionary,Miscellaneous Amusement & Recreation Services,US Stocks
WDC,Western Digital,Technology,Electronic Components,US Stocks
WDAY,"Workday, Inc.",Technology,EDP Services,US Stocks
XEL,Xcel Energy,Utilities,Power Generation,US Stocks
ZS,Zscaler,Technology,EDP Services,US Stocks

In [7]:
# Remove symbols without enough data
# nasdaq100.drop('SOLS', inplace=True)

In [8]:
# Make symbols list.
symbols = list(nasdaq100.index)

In [9]:
# Get the timeseries for the symbols and compile into a single csv.
bb.fetch_timeseries(symbols, refresh=refresh_timeseries, throttle_limit=throttle_limit, wait_time=wait_time)
bb.compile_timeseries(symbols)

ADBE AMD ABNB ALNY GOOGL GOOG AMZN AEP AMGN ADI AAPL AMAT APP ARM ASML ADSK ADP AXON BKR BKNG AVGO CDNS CHTR CTAS CSCO CCEP CTSH CMCSA CEG CPRT COST CRWD CSX DDOG DXCM FANG DASH EA EXC FAST FER FTNT GEHC GILD HON IDXX INSM INTC INTU ISRG KDP KLAC KHC LRCX LIN LITE MAR MRVL MELI META MCHP MU MSFT MSTR MDLZ MPWR MNST NFLX NVDA NXPI ORLY ODFL PCAR PLTR PANW PAYX PYPL PDD PEP QCOM REGN ROP ROST SNDK STX SHOP SBUX SNPS TMUS TTWO TSLA TXN TRI VRSK VRTX WMT WBD WDC WDAY XEL
Throttle limit reached. Waiting for 30 seconds...
ZS

In [10]:
# Read symbols timeseries into a dataframe.
df = pd.read_csv('symbols-timeseries.csv', skip_blank_lines=True, comment='#')
df.set_index("Date", inplace=True)
df

,ADBE,AMD,ABNB,ALNY,GOOGL,GOOG,AMZN,AEP,AMGN,ADI,...,TXN,TRI,VRSK,VRTX,WMT,WBD,WDC,WDAY,XEL,ZS
Date,,,,,,,,,,,,,,,,,,,,,
2019-01-02,224.57,18.83,NaN,72.76,52.27,51.84,76.96,56.13,152.61,75.15,...,76.54,41.03,103.58,164.08,27.91,25.83,27.32,159.74,38.74,39.81
2019-01-03,215.70,17.05,NaN,73.21,50.82,50.36,75.01,55.99,150.29,70.61,...,72.02,40.44,100.41,163.73,27.77,25.68,25.46,154.02,38.59,39.32
2019-01-04,226.19,19.00,NaN,75.20,53.43,53.07,78.77,56.51,155.43,72.32,...,75.28,41.07,104.85,172.70,27.94,26.14,26.54,163.35,38.97,41.77
2019-01-07,229.26,20.57,NaN,81.78,53.32,52.95,81.48,56.19,157.52,72.78,...,76.58,40.97,104.95,175.85,28.27,26.53,27.48,163.50,38.80,43.56
2019-01-08,232.68,20.75,NaN,85.34,53.79,53.34,82.83,56.89,159.54,74.55,...,76.48,41.09,105.89,178.19,28.47,27.24,27.21,166.95,39.25,43.98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-04-23,238.98,305.33,141.87,313.79,338.69,337.55,255.08,134.11,346.01,402.78,...,280.80,88.14,177.14,435.10,131.78,26.90,403.01,114.67,79.48,132.97
2026-04-24,245.44,347.81,142.82,305.54,344.19,342.11,263.99,133.76,341.97,398.48,...,275.74,87.72,177.59,430.29,129.67,27.07,403.89,119.76,79.15,135.50
2026-04-27,239.31,334.63,141.06,308.51,350.13,348.31,261.12,134.10,337.63,391.52,...,268.14,87.03,174.90,426.01,127.35,26.82,400.63,117.83,79.41,134.11
2026-04-28,243.20,323.21,139.04,302.11,349.57,347.29,259.70,134.61,337.02,382.21,...,263.66,87.86,176.66,430.14,127.35,26.95,390.89,121.18,79.48,136.07
2026-04-29,243.57,337.11,140.28,301.19,349.73,347.10,263.04,133.47,335.49,388.25,...,267.86,91.18,188.19,423.24,127.77,27.05,412.65,122.43,78.82,134.73

In [11]:
# Calculate Annual Returns.
annual_returns = bb.annualized_returns(df, timeperiod='daily', years=1)
annual_returns

ADBE    -33.92
AMD     249.74
ABNB     13.77
ALNY     18.18
GOOGL   118.64
         ...
WBD     210.92
WDC     913.30
WDAY    -48.95
XEL      16.86
ZS      -38.72
Length: 101, dtype: float64

In [12]:
# Calculate 3 month, 6 months, 1 year, 1-1 year, 3 year, and 5 year annualized returns.
annual_returns_3mo = bb.annualized_returns(df, timeperiod='daily', years=3/12)
annual_returns_6mo = bb.annualized_returns(df, timeperiod='daily', years=6/12)
annual_returns_1yr = bb.annualized_returns(df, timeperiod='daily', years=1)
annual_returns_1_1yr = bb.annualized_returns(df, timeperiod='daily', years=1, offset=1)
annual_returns_3yr = bb.annualized_returns(df, timeperiod='daily', years=3)
annual_returns_5yr = bb.annualized_returns(df, timeperiod='daily', years=5)

In [13]:
# Calculate 20 day annualized volatility.
daily_returns = df.pct_change()
years = bb.TRADING_DAYS_PER_MONTH / bb.TRADING_DAYS_PER_YEAR
vola = bb.annualized_standard_deviation(daily_returns, timeperiod='daily', years=years)

In [14]:
# Calculate 20 day annualized downside volatility.
ds_vola = bb.annualized_standard_deviation(daily_returns, timeperiod='daily', years=years, downside=True)

In [15]:
# Resample df on a monthly basis.
df.index = pd.to_datetime(df.index)
monthly = df.resample('ME').ffill()

In [16]:
# Calculate monthly returns.
monthly_returns = monthly.pct_change()

In [17]:
# Calculate 1 year, 3 year, and 5 year annualized standard deviation.
std_dev_1yr = bb.annualized_standard_deviation(monthly_returns, timeperiod='monthly', years=1)
std_dev_3yr = bb.annualized_standard_deviation(monthly_returns, timeperiod='monthly', years=3)
std_dev_5yr = bb.annualized_standard_deviation(monthly_returns, timeperiod='monthly', years=5)

In [18]:
# Read investment-options-header.csv
lines = []
with open('investment-options-in.csv', 'r') as f:
    lines = [line.strip() for line in f]

In [19]:
# For each symbol, write out the 1 Yr, 3 Yr, 5 Yr, and std dev.
out = lines.copy()

# This is still slow (2.53 s).
for i, (index, row) in enumerate(nasdaq100.iterrows()):

    symbol = index
    description = row['Description']
    asset_class = row['Asset Class']

    ret_3mo = annual_returns_3mo[symbol]
    ret_6mo = annual_returns_6mo[symbol]
    ret_1yr = annual_returns_1yr[symbol]
    ret_1_1yr = annual_returns_1_1yr[symbol]
    ret_3yr = annual_returns_3yr[symbol]
    ret_5yr = annual_returns_5yr[symbol]
    
    if np.isnan(ret_3yr): ret_3yr = ret_1yr
    if np.isnan(ret_5yr): ret_5yr = ret_3yr

    _vola = vola[symbol]*100
    _ds_vola = ds_vola[symbol]*100
    sd_1yr = std_dev_1yr[symbol]*100
    sd_3yr = std_dev_3yr[symbol]*100
    sd_5yr = std_dev_5yr[symbol]*100

    out.append(
        f'"{symbol}","{description}","{asset_class}",'
        f'"{ret_3mo:0.2f}","{ret_6mo:0.2f}","{ret_1yr:0.2f}","{ret_1_1yr:0.2f}","{ret_3yr:0.2f}",'
        f'"{ret_5yr:0.2f}","{_vola:0.2f}","{_ds_vola:0.2f}","{sd_1yr:0.2f}","{sd_3yr:0.2f}","{sd_5yr:0.2f}"'
    )

In [20]:
# Write out asset-classes.csv
with open('investment-options.csv', 'w') as f:
    for line in out:
        f.write(line + '\n')