## S&P 400 Galaxy

Use this utlity to update the returns and std_dev fields within investment-options.csv

Globals

In [1]:
# Set refresh_timeseries=True to download timeseries.  Otherwise /symbol-cache is used.
refresh_timeseries = True
throttle_limit=100
wait_time=30

In [2]:
%%javascript
IPython.OutputArea.prototype._should_scroll = function(lines) {
    return false;
}

In [3]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

import brownbear as bb

# Format price data.
pd.options.display.float_format = '{:0.2f}'.format

In [4]:
# Read in sp400.csv
sp400 = pd.read_csv('sp400.csv')
sp400.drop(columns=['SEC filings'], inplace=True)
sp400.rename(columns={'Security':'Description',
                      'GICS Sector':'Asset Class',
                      'GICS Sub-Industry': 'GICS Sub Industry'}, inplace=True)
sp400.set_index("Symbol", inplace=True)
sp400

,Description,Asset Class,GICS Sub Industry,Headquarters Location
Symbol,,,,
AA,Alcoa,Materials,Aluminum,"Pittsburgh, Pennsylvania"
AAL,American Airlines Group,Industrials,Passenger Airlines,"Fort Worth, Texas"
AAON,AAON,Industrials,Building Products,"Tulsa, Oklahoma"
ACI,Albertsons,Consumer Staples,Food Retail,"Boise, Idaho"
ACM,AECOM,Industrials,Construction & Engineering,"Dallas, Texas"
...,...,...,...,...
WWD,"Woodward, Inc.",Industrials,Electrical Components & Equipment,"Fort Collins, Colorado"
XPO,"XPO, Inc.",Industrials,Cargo Ground Transportation,"Greenwich, Connecticut"
XRAY,Dentsply Sirona,Health Care,Health Care Supplies,"Charlotte, North Carolina"
YETI,Yeti Holdings,Consumer Discretionary,Leisure Products,"Austin, Texas"
ZION,Zions Bancorporation,Financials,Regional Banks,"Salt Lake City, Utah"

In [5]:
# Read in gics-2-asset-class.csv
gics2asset_class = pd.read_csv('gics-2-asset-class.csv', skip_blank_lines=True, comment='#')
gics2asset_class.set_index("GICS", inplace=True)
gics2asset_class = gics2asset_class['Asset Class'].to_dict()
gics2asset_class

{'Energy': 'US Stocks:Energy',
 'Materials': 'US Stocks:Materials',
 'Industrials': 'US Stocks:Industrials',
 'Consumer Discretionary': 'US Stocks:Consumer Discretionary',
 'Consumer Staples': 'US Stocks:Consumer Staples',
 'Health Care': 'US Stocks:Healthcare',
 'Financials': 'US Stocks:Financials',
 'Information Technology': 'US Stocks:Technology',
 'Communication Services': 'US Stocks:Communication Services',
 'Utilities': 'US Stocks:Utilities',
 'Real Estate': 'US Stocks:Real Estate'}

In [6]:
# Map sp400 GICS sectors to brownbear defined asset classes.
def _asset_class(row):
    return gics2asset_class[row['Asset Class']]

sp400['Asset Class'] = sp400.apply(_asset_class, axis=1)

# Yahoo finance uses '-' where '.' is used in symbol names.
sp400.index = sp400.index.str.replace('.', '-', regex=False)
sp400

,Description,Asset Class,GICS Sub Industry,Headquarters Location
Symbol,,,,
AA,Alcoa,US Stocks:Materials,Aluminum,"Pittsburgh, Pennsylvania"
AAL,American Airlines Group,US Stocks:Industrials,Passenger Airlines,"Fort Worth, Texas"
AAON,AAON,US Stocks:Industrials,Building Products,"Tulsa, Oklahoma"
ACI,Albertsons,US Stocks:Consumer Staples,Food Retail,"Boise, Idaho"
ACM,AECOM,US Stocks:Industrials,Construction & Engineering,"Dallas, Texas"
...,...,...,...,...
WWD,"Woodward, Inc.",US Stocks:Industrials,Electrical Components & Equipment,"Fort Collins, Colorado"
XPO,"XPO, Inc.",US Stocks:Industrials,Cargo Ground Transportation,"Greenwich, Connecticut"
XRAY,Dentsply Sirona,US Stocks:Healthcare,Health Care Supplies,"Charlotte, North Carolina"
YETI,Yeti Holdings,US Stocks:Consumer Discretionary,Leisure Products,"Austin, Texas"
ZION,Zions Bancorporation,US Stocks:Financials,Regional Banks,"Salt Lake City, Utah"

In [7]:
# Drop invalid symbols.
sp400.drop(['CVLT'], inplace=True)

In [8]:
# Make symbols list.
symbols = list(sp400.index)

In [9]:
# Get the timeseries for the symbols and compile into a single csv.
bb.fetch_timeseries(symbols, refresh=refresh_timeseries, throttle_limit=throttle_limit, wait_time=wait_time)
bb.compile_timeseries(symbols)

AA AAL AAON ACI ACM ADC AEIS AFG AGCO AHR AIT ALGM ALK ALLY ALV AM AMG AMH AMKR AN ANF APG APPF AR ARMK ARW ARWR ASB ASH ATI ATR AVAV AVNT AVT AVTR AXTA AYI BAH BBWI BC BCO BDC BHF BILL BIO BJ BKH BLD BLKB BMRN BRBR BRKR BROS BRX BSY BURL BWA BWXT BYD CACI CAR CART CAVA CBSH CBT CCK CDP CELH CFR CG CGNX CHDN CHE CHH CHRD CHWY CLF CLH CMC CNH CNM CNO CNX CNXC COKE COLB COLM COTY CPRI CR CRBG CROX CRS CRUS CSL CTRE CUBE CUZ CW CXT
Throttle limit reached. Waiting for 30 seconds...
CYTK DAR DBX DCI DINO DKS DLB DOCN DOCS DOCU DT DTM DUOL DY EEFT EGP EHC ELAN ELF ELS ENS ENSG ENTG EPR EQH ESAB ESNT EVR EWBC EXEL EXLS EXP EXPO FAF FBIN FCFS FCN FFIN FHI FHN FIVE FLEX FLG FLR FLS FN FNB FND FNF FOUR FR FTI G GAP GATX GBCI GEF GGG GHC GLPI GME GMED GNTX GPK GT GTLS GWRE GXO H HAE HALO HGV HIMS HL HLI HLNE HOG HOMB HQY HR HRB HWC HXL IBOC IDA IDCC ILMN INGR IPGP IRT ITT JAZZ JEF JHG JLL KBH KBR KD KEX KNF
Throttle limit reached. Waiting for 30 seconds...
KNSL KNX KRC KRG KTOS LAD LAMR LEA LECO LFUS LIVN LNTH LOPE LPX LSCC LSTR M MANH MASI MAT MEDP MIDD MKSI MLI MMS MOG-A MORN MP MSA MSM MTDR MTG MTN MTSI MTZ MUR MUSA MZTI NBIX NEU NFG NJR NLY NNN NOV NOVT NSA NTNX NVST NVT NWE NXST NXT NYT OC OGE OGS OHI OKTA OLED OLLI OLN ONB ONTO OPCH ORA ORI OSK OVV OZK P PAG PATH PB PBF PCTY PEGA PEN PFGC PII PINS PK PLNT PNFP POR POST PPC PR PRI PSN PVH QLYS R RBA RBC REXR RGA RGEN RGLD RH
Throttle limit reached. Waiting for 30 seconds...
RLI RMBS RNR ROIV RPM RRC RRX RS RYAN RYN SAIA SAIC SAM SARO SBRA SCI SEIC SF SFM SGI SHC SIGI SITM SLAB SLGN SLM SMG SN SNX SOLS SON SPXC SR SSB SSD ST STAG STRL STWD SWX SYNA TCBI TEX THC THG THO TKR TLN TMHC TNL TOL TREX TRU TTC TTEK TTMI TWLO TXNM TXRH UBSI UFPI UGI ULS UMBF UNM USFD UTHR VAL VC VFC VICR VLY VMI VNO VNOM VNT VOYA VVV WAL WBS WCC WEX WFRD WH WHR WING WLK WMG WMS WPC WSO WTFC WTRG WTS WWD XPO XRAY YETI ZION

In [10]:
# Read symbols timeseries into a dataframe.
df = pd.read_csv('symbols-timeseries.csv', skip_blank_lines=True, comment='#')
df.set_index("Date", inplace=True)
df

,AA,AAL,AAON,ACI,ACM,ADC,AEIS,AFG,AGCO,AHR,...,WPC,WSO,WTFC,WTRG,WTS,WWD,XPO,XRAY,YETI,ZION
Date,,,,,,,,,,,,,,,,,,,,,
2019-01-02,24.98,31.96,22.46,NaN,25.76,42.62,42.49,47.69,45.66,NaN,...,41.36,110.09,59.65,26.71,60.75,70.66,19.94,33.38,16.17,32.38
2019-01-03,24.98,29.58,21.63,NaN,25.27,43.58,40.18,47.49,44.69,NaN,...,41.87,108.61,58.90,27.01,59.44,67.87,19.14,33.40,15.04,32.20
2019-01-04,26.98,31.53,22.81,NaN,26.58,43.43,42.14,48.22,47.32,NaN,...,42.54,113.02,60.62,27.22,61.14,69.58,19.69,34.37,15.30,33.19
2019-01-07,27.06,32.43,23.15,NaN,27.09,43.64,43.17,47.84,48.90,NaN,...,42.95,113.00,60.85,26.98,62.37,69.78,20.47,34.99,16.26,33.32
2019-01-08,26.90,31.90,23.27,NaN,27.41,44.66,42.12,47.89,49.48,NaN,...,43.93,113.58,61.52,27.31,63.66,73.02,20.83,34.75,16.83,33.63
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-04-23,65.27,11.78,98.64,16.69,80.46,76.70,382.35,132.23,119.23,50.58,...,73.72,437.49,149.99,39.96,302.77,367.19,224.76,11.90,39.92,62.16
2026-04-24,65.90,12.10,99.52,16.62,80.37,76.15,387.12,130.28,115.83,50.10,...,73.12,440.64,147.36,39.16,300.60,364.62,223.68,11.91,39.96,60.88
2026-04-27,67.25,11.68,91.58,16.57,81.99,75.44,385.56,129.55,117.21,50.32,...,72.40,456.86,148.68,39.05,303.24,366.30,220.00,11.96,39.38,62.14
2026-04-28,63.07,11.64,88.02,16.56,81.06,76.31,368.97,131.37,114.97,50.32,...,72.66,438.47,149.99,39.27,297.59,363.64,222.01,11.78,39.42,62.70
2026-04-29,62.36,11.31,86.41,16.48,81.96,75.81,361.28,129.42,114.14,50.21,...,72.06,428.51,147.48,39.13,296.67,360.66,216.71,11.48,38.53,62.11

In [11]:
# Calculate Annual Returns.
annual_returns = bb.annualized_returns(df, timeperiod='daily', years=1)
annual_returns

AA     147.11
AAL     14.82
AAON    -2.16
ACI    -21.39
ACM    -14.95
        ...
WWD     99.82
XPO    122.20
XRAY   -14.07
YETI    34.53
ZION    43.91
Length: 399, dtype: float64

In [12]:
# Calculate 3 month, 6 months, 1 year, 1-1 year, 3 year, and 5 year annualized returns.
annual_returns_3mo = bb.annualized_returns(df, timeperiod='daily', years=3/12)
annual_returns_6mo = bb.annualized_returns(df, timeperiod='daily', years=6/12)
annual_returns_1yr = bb.annualized_returns(df, timeperiod='daily', years=1)
annual_returns_1_1yr = bb.annualized_returns(df, timeperiod='daily', years=1, offset=1)
annual_returns_3yr = bb.annualized_returns(df, timeperiod='daily', years=3)
annual_returns_5yr = bb.annualized_returns(df, timeperiod='daily', years=5)

In [13]:
# Calculate 20 day annualized volatility.
daily_returns = df.ffill().pct_change()
years = bb.TRADING_DAYS_PER_MONTH / bb.TRADING_DAYS_PER_YEAR
vola = bb.annualized_standard_deviation(daily_returns, timeperiod='daily', years=years)

In [14]:
# Calculate 20 day annualized downside volatility.
ds_vola = bb.annualized_standard_deviation(daily_returns, timeperiod='daily', years=years, downside=True)

In [15]:
# Resample df on a monthly basis.
df.index = pd.to_datetime(df.index)
monthly = df.resample('ME').ffill()

In [16]:
# Calculate monthly returns.
monthly_returns = monthly.ffill().pct_change()

In [17]:
# Calculate 1 year, 3 year, and 5 year annualized standard deviation.
std_dev_1yr = bb.annualized_standard_deviation(monthly_returns, timeperiod='monthly', years=1)
std_dev_3yr = bb.annualized_standard_deviation(monthly_returns, timeperiod='monthly', years=3)
std_dev_5yr = bb.annualized_standard_deviation(monthly_returns, timeperiod='monthly', years=5)

In [18]:
# Read investment-options-header.csv
lines = []
with open('investment-options-in.csv', 'r') as f:
    lines = [line.strip() for line in f]

In [19]:
# For each symbol, write out the 1 Yr, 3 Yr, 5 Yr, and std dev.
out = lines.copy()

# This is still slow (2.53 s).
for i, (index, row) in enumerate(sp400.iterrows()):

    symbol = index
    description = row['Description']
    asset_class = row['Asset Class']

    ret_3mo = annual_returns_3mo[symbol]
    ret_6mo = annual_returns_6mo[symbol]
    ret_1yr = annual_returns_1yr[symbol]
    ret_1_1yr = annual_returns_1_1yr[symbol]
    ret_3yr = annual_returns_3yr[symbol]
    ret_5yr = annual_returns_5yr[symbol]
    
    if np.isnan(ret_3yr): ret_3yr = ret_1yr
    if np.isnan(ret_5yr): ret_5yr = ret_3yr

    _vola = vola[symbol]*100
    _ds_vola = ds_vola[symbol]*100
    sd_1yr = std_dev_1yr[symbol]*100
    sd_3yr = std_dev_3yr[symbol]*100
    sd_5yr = std_dev_5yr[symbol]*100

    out.append(
        f'"{symbol}","{description}","{asset_class}",'
        f'"{ret_3mo:0.2f}","{ret_6mo:0.2f}","{ret_1yr:0.2f}","{ret_1_1yr:0.2f}","{ret_3yr:0.2f}",'
        f'"{ret_5yr:0.2f}","{_vola:0.2f}","{_ds_vola:0.2f}","{sd_1yr:0.2f}","{sd_3yr:0.2f}","{sd_5yr:0.2f}"'
    )

In [20]:
# Write out asset-classes.csv
with open('investment-options.csv', 'w') as f:
    for line in out:
        f.write(line + '\n')