## ETF Galaxy

Use this utlity to update the returns and std_dev fields within investment-options.csv

Globals

In [1]:
# Set refresh_timeseries=True to download timeseries.  Otherwise /symbol-cache is used.
refresh_timeseries = False
throttle_limit=100
wait_time=30

In [2]:
%%javascript
IPython.OutputArea.prototype._should_scroll = function(lines) {
    return false;
}

In [3]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

import brownbear as bb

# Format price data.
pd.options.display.float_format = '{:0.2f}'.format

In [4]:
# Read in investment options input csv.
df = pd.read_csv('investment-options-in.csv', skip_blank_lines=True, comment='#')
symbols = list(df['Investment Option'])
df

,Investment Option,Description,Asset Class,3 mo,6 mo,1 Yr,1-1 Yr,3 Yr,5 Yr,Vola,DS Vola,SD 1 Yr,SD 3 Yr,SD 5 Yr
0,SPY,S&P 500 ETF,US Stocks:Large Cap,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,DIA,DJIA ETF,US Stocks:Large Cap,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,QQQ,Nasdaq 100 ETF,US Stocks:Growth,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,VTI,Vanguard Total Stock Market Index ETF,US Stocks:Total Stock Market,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,IWM,Russell 2000 ETF,US Stocks:Small Cap,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,OIH,Oil Services ETF,US Stocks:Energy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,VDE,Energy ETF,US Stocks:Energy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,QTUM,Defiance Quantum ETF,US Stocks:Technology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,NLR,VanEck Uranium and Nuclear ETF,US Stocks:Energy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,NUKZ,Range Nuclear Renaissance ETF,US Stocks:Energy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Eliminate repeat symbols.
symbols = set(list(symbols))

In [6]:
# Get the timeseries for the symbols and compile into a single csv.
bb.fetch_timeseries(symbols, refresh=refresh_timeseries, throttle_limit=throttle_limit, wait_time=wait_time)
bb.compile_timeseries(symbols)

SLV FXE EWT RSP VCSH XLY VTI QTUM FXC BND VNQ XLC NOBL SDY EFA FXF XLU DBB XLF DIA VPL IWF EWJ LQD UNG XLV MDY GLD DBA IBIT IWM GDX QQQ XLE SPY PPLT BNDX BWZ XOP EWH FXA OIH SHV ETHE VDE AGG XLK VCIT JPST XLP PEY GBTC XLB PGX IYR SPYD SPSM EBND FXY FBTC UGA DBE BWX USO EEM XHB NLR JNK UUP IEUR BIL CORN VXUS IBND EWZ PALL FXI SHY CANE PFF IWD XLI BITW NUKZ TLT DBP XLRE FXB CPER

In [7]:
# Read symbols timeseries into a dataframe.
df = pd.read_csv('symbols-timeseries.csv', skip_blank_lines=True, comment='#')
df.set_index("Date", inplace=True)
df

,SLV,FXE,EWT,RSP,VCSH,XLY,VTI,QTUM,FXC,BND,...,PFF,IWD,XLI,BITW,NUKZ,TLT,DBP,XLRE,FXB,CPER
Date,,,,,,,,,,,,,,,,,,,,,
2019-01-02,14.56,103.06,20.34,80.56,62.40,46.65,114.38,18.90,68.38,63.68,...,22.75,95.40,57.43,NaN,NaN,98.69,31.99,23.83,111.23,16.28
2019-01-03,14.75,103.50,19.70,79.00,62.52,45.64,111.73,18.19,68.94,63.93,...,22.79,93.84,55.68,NaN,NaN,99.82,32.38,23.94,111.41,16.10
2019-01-04,14.73,103.52,20.08,81.63,62.35,47.15,115.43,18.91,69.34,63.73,...,23.03,96.54,57.79,NaN,NaN,98.66,32.16,24.18,112.34,16.52
2019-01-07,14.67,104.21,20.26,82.48,62.33,48.22,116.60,19.14,69.82,63.64,...,23.10,97.08,58.26,NaN,NaN,98.37,32.22,24.39,112.59,16.45
2019-01-08,14.69,103.88,20.21,83.37,62.30,48.75,117.80,19.16,69.98,63.56,...,23.16,97.87,59.06,NaN,NaN,98.11,32.15,24.81,112.16,16.57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-04-23,68.38,107.70,84.24,202.45,78.75,117.74,349.80,129.75,71.34,73.24,...,31.21,227.49,174.07,50.49,73.50,85.89,110.56,43.96,129.12,36.96
2026-04-24,68.79,108.04,88.09,202.03,78.87,118.69,352.05,132.79,71.48,73.37,...,31.24,227.65,172.47,50.42,73.54,86.05,110.91,43.83,129.80,36.94
2026-04-27,68.33,107.95,87.35,201.79,78.79,117.84,352.53,131.89,71.66,73.25,...,31.21,227.67,172.51,49.76,74.02,85.63,110.25,43.49,129.77,36.93
2026-04-28,66.20,107.92,87.24,200.76,78.77,117.01,350.63,128.98,71.40,73.23,...,31.01,227.08,170.98,49.63,72.24,85.72,108.01,43.91,129.64,36.24
2026-04-29,64.84,107.61,87.19,200.41,78.58,116.84,350.21,129.94,71.42,72.90,...,30.90,227.07,169.93,48.82,70.36,85.05,106.51,43.64,129.26,35.97

In [8]:
# Calculate Annual Returns.
annual_returns = bb.annualized_returns(df, timeperiod='daily', years=1)
annual_returns

SLV    114.77
FXE      2.91
EWT     96.25
RSP     21.35
VCSH     4.62
        ...
TLT      0.16
DBP     45.59
XLRE    10.73
FXB      2.55
CPER    18.17
Length: 89, dtype: float64

In [9]:
# Calculate 3 month, 6 months, 1 year, 1-1 year, 3 year, and 5 year annualized returns.
annual_returns_3mo = bb.annualized_returns(df, timeperiod='daily', years=3/12)
annual_returns_6mo = bb.annualized_returns(df, timeperiod='daily', years=6/12)
annual_returns_1yr = bb.annualized_returns(df, timeperiod='daily', years=1)
annual_returns_1_1yr = bb.annualized_returns(df, timeperiod='daily', years=1, offset=1)
annual_returns_3yr = bb.annualized_returns(df, timeperiod='daily', years=3)
annual_returns_5yr = bb.annualized_returns(df, timeperiod='daily', years=5)

In [10]:
# Calculate 20 day annualized volatility.
daily_returns = df.pct_change(fill_method=None)
years = bb.TRADING_DAYS_PER_MONTH / bb.TRADING_DAYS_PER_YEAR
vola = bb.annualized_standard_deviation(daily_returns, timeperiod='daily', years=years)

In [11]:
# Calculate 20 day annualized downside volatility.
ds_vola = bb.annualized_standard_deviation(daily_returns, timeperiod='daily', years=years, downside=True)

In [12]:
# Resample df on a monthly basis.
df.index = pd.to_datetime(df.index)
monthly = df.resample('ME').ffill()

In [13]:
# Calculate monthly returns.
monthly_returns = monthly.pct_change(fill_method=None)

In [14]:
# Calculate 1 year, 3 year, and 5 year annualized standard deviation.
std_dev_1yr = bb.annualized_standard_deviation(monthly_returns, timeperiod='monthly', years=1)
std_dev_3yr = bb.annualized_standard_deviation(monthly_returns, timeperiod='monthly', years=3)
std_dev_5yr = bb.annualized_standard_deviation(monthly_returns, timeperiod='monthly', years=5)

In [15]:
# Read investment-options-in.csv
lines = []
with open('investment-options-in.csv', 'r') as f:
    lines = [line.strip() for line in f]

In [16]:
# For each etf, write out the 1 Yr, 3 Yr, 5 Yr, and std dev.
out = []
for line in lines:
    # Copy empty and comment lines.
    if not line or line.startswith('#'):
        out.append(line)
        continue
    # Split line by comma delimiter; strip the fields.
    fields = line.split(',')
    fields = [field.strip() for field in fields]
    symbol = fields[0].strip('\"')
    # Copy header.
    if symbol == 'Investment Option':
        out.append(line)
        continue
    ret_3mo = annual_returns_3mo[symbol]
    ret_6mo = annual_returns_6mo[symbol]
    ret_1yr = annual_returns_1yr[symbol]
    ret_1_1yr = annual_returns_1_1yr[symbol]
    ret_3yr = annual_returns_3yr[symbol]
    ret_5yr = annual_returns_5yr[symbol]
    
    if np.isnan(ret_3yr): ret_3yr = ret_1yr
    if np.isnan(ret_5yr): ret_5yr = ret_3yr

    _vola = vola[symbol]*100
    _ds_vola = ds_vola[symbol]*100
    sd_1yr = std_dev_1yr[symbol]*100
    sd_3yr = std_dev_3yr[symbol]*100
    sd_5yr = std_dev_5yr[symbol]*100

    out.append(
        f'{fields[0]},{fields[1]},{fields[2]},'
        f'"{ret_3mo:0.2f}","{ret_6mo:0.2f}","{ret_1yr:0.2f}","{ret_1_1yr:0.2f}","{ret_3yr:0.2f}",'
        f'"{ret_5yr:0.2f}","{_vola:0.2f}","{_ds_vola:0.2f}","{sd_1yr:0.2f}","{sd_3yr:0.2f}","{sd_5yr:0.2f}"'
    )

In [17]:
# Write out asset-classes.csv
with open('investment-options.csv', 'w') as f:
    for line in out:
        f.write(line + '\n')