## DOW30 Galaxy

Use this utlity to update the returns and std_dev fields within investment-options.csv

Globals

In [1]:
# Set refresh_timeseries=True to download timeseries.  Otherwise /symbol-cache is used.
refresh_timeseries = False
throttle_limit=100
wait_time=30

In [2]:
%%javascript
IPython.OutputArea.prototype._should_scroll = function(lines) {
    return false;
}

In [3]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

import brownbear as bb

# Format price data.
pd.options.display.float_format = '{:0.2f}'.format

In [4]:
# Read in dow30.csv
dow30 = pd.read_csv('dow30.csv')

# Remove the exchange from the beginning of the symbol.
def _symbol(row):
    return row['Symbol'].split(':')[-1].strip()

dow30['Symbol'] = dow30.apply(_symbol, axis=1)
dow30.drop(columns=['Exchange', 'Date added', 'Notes', 'Index weighting'], inplace=True)
dow30.rename(columns={'Symbol': 'Symbol',
                      'Company':'Description',
                      'Sector':'Asset Class'}, inplace=True)

dow30.set_index("Symbol", inplace=True)
dow30

                      Description             Asset Class
Symbol
MMM                            3M             Industrials
AXP              American Express              Financials
AMGN                        Amgen             Health Care
AMZN                       Amazon  Consumer Discretionary
AAPL                        Apple  Information Technology
BA                         Boeing             Industrials
CAT                   Caterpillar             Industrials
CVX                       Chevron                  Energy
CSCO                        Cisco  Information Technology
KO                      Coca-Cola        Consumer Staples
DIS                        Disney  Communication Services
GS                  Goldman Sachs              Financials
HD                     Home Depot  Consumer Discretionary
HON                     Honeywell             Industrials
IBM                           IBM  Information Technology
JNJ             Johnson & Johnson             Health Care
JPM                JPMorgan Chase              Financials
MCD                    McDonald's  Consumer Discretionary
MRK                         Merck             Health Care
MSFT                    Microsoft  Information Technology
NKE                          Nike  Consumer Discretionary
NVDA                       Nvidia  Information Technology
PG               Procter & Gamble        Consumer Staples
CRM                    Salesforce  Information Technology
SHW              Sherwin-Williams               Materials
TRV     Travelers Companies, Inc.              Financials
UNH            UnitedHealth Group             Health Care
VZ                        Verizon  Communication Services
V                            Visa              Financials
WMT                       Walmart        Consumer Staples

In [5]:
# Read in gics-2-asset-class.csv
gics2asset_class = pd.read_csv('gics-2-asset-class.csv', skip_blank_lines=True, comment='#')
gics2asset_class.set_index("GICS", inplace=True)
gics2asset_class = gics2asset_class['Asset Class'].to_dict()
gics2asset_class

{'Conglomerate': 'US Stocks:Industrials',
 'Industrials': 'US Stocks:Industrials',
 'Financial services': 'US Stocks:Financials',
 'Financials': 'US Stocks:Financials',
 'Pharmaceutical industry': 'US Stocks:Healthcare',
 'Biopharmaceutical': 'US Stocks:Healthcare',
 'Health Care': 'US Stocks:Healthcare',
 'Information technology': 'US Stocks:Technology',
 'Aerospace and defense': 'US Stocks:Industrials',
 'Construction and mining': 'US Stocks:Industrials',
 'Petroleum industry': 'US Stocks:Energy',
 'Energy': 'US Stocks:Energy',
 'Food industry': 'US Stocks:Consumer Staples',
 'Drink industry': 'US Stocks:Consumer Staples',
 'Consumer Staples': 'US Stocks:Consumer Staples',
 'Chemical industry': 'US Stocks:Materials',
 'Retailing': 'US Stocks:Consumer Discretionary',
 'Apparel': 'US Stocks:Consumer Discretionary',
 'Consumer Discretionary': 'US Stocks:Consumer Discretionary',
 'Fast-moving consumer goods': 'US Stocks:Consumer Staples',
 'Managed health care': 'US Stocks:Healthcare',
 'Telecommunication': 'US Stocks:Communication Services',
 'Broadcasting and entertainment': 'US Stocks:Communication Services',
 'Communication Services': 'US Stocks:Communication Services',
 'Home Improvement': 'US Stocks:Consumer Discretionary',
 'Semiconductor industry': 'US Stocks:Technology',
 'Information Technology': 'US Stocks:Technology',
 'Clothing industry': 'US Stocks:Consumer Discretionary',
 'Insurance': 'US Stocks:Financials',
 'Telecommunications industry': 'US Stocks:Communication Services',
 'Specialty chemicals': 'US Stocks:Materials',
 'Materials': 'US Stocks:Materials'}

In [6]:
# Map dow30 GICS sectors to brownbear defined asset classes.
def _asset_class(row):
    return gics2asset_class[row['Asset Class']]

dow30['Asset Class'] = dow30.apply(_asset_class, axis=1)

# Yahoo finance uses '-' where '.' is used in symbol names.
dow30.index = dow30.index.str.replace('.', '-', regex=False)
dow30

                      Description                       Asset Class
Symbol
MMM                            3M             US Stocks:Industrials
AXP              American Express              US Stocks:Financials
AMGN                        Amgen              US Stocks:Healthcare
AMZN                       Amazon  US Stocks:Consumer Discretionary
AAPL                        Apple              US Stocks:Technology
BA                         Boeing             US Stocks:Industrials
CAT                   Caterpillar             US Stocks:Industrials
CVX                       Chevron                  US Stocks:Energy
CSCO                        Cisco              US Stocks:Technology
KO                      Coca-Cola        US Stocks:Consumer Staples
DIS                        Disney  US Stocks:Communication Services
GS                  Goldman Sachs              US Stocks:Financials
HD                     Home Depot  US Stocks:Consumer Discretionary
HON                     Honeywell             US Stocks:Industrials
IBM                           IBM              US Stocks:Technology
JNJ             Johnson & Johnson              US Stocks:Healthcare
JPM                JPMorgan Chase              US Stocks:Financials
MCD                    McDonald's  US Stocks:Consumer Discretionary
MRK                         Merck              US Stocks:Healthcare
MSFT                    Microsoft              US Stocks:Technology
NKE                          Nike  US Stocks:Consumer Discretionary
NVDA                       Nvidia              US Stocks:Technology
PG               Procter & Gamble        US Stocks:Consumer Staples
CRM                    Salesforce              US Stocks:Technology
SHW              Sherwin-Williams               US Stocks:Materials
TRV     Travelers Companies, Inc.              US Stocks:Financials
UNH            UnitedHealth Group              US Stocks:Healthcare
VZ                        Verizon  US Stocks:Communication Services
V                            Visa              US Stocks:Financials
WMT                       Walmart        US Stocks:Consumer Staples

In [7]:
# Make symbols list.
symbols = list(dow30.index)
#symbols

In [8]:
# Get the timeseries for the symbols and compile into a single csv.
bb.fetch_timeseries(symbols, refresh=refresh_timeseries, throttle_limit=throttle_limit, wait_time=wait_time)
bb.compile_timeseries(symbols)

MMM AXP AMGN AMZN AAPL BA CAT CVX CSCO KO DIS GS HD HON IBM JNJ JPM MCD MRK MSFT NKE NVDA PG CRM SHW TRV UNH VZ V WMT

In [9]:
# Read symbols timeseries into a dataframe.
df = pd.read_csv('symbols-timeseries.csv', skip_blank_lines=True, comment='#')
df.set_index("Date", inplace=True)
df

,MMM,AXP,AMGN,AMZN,AAPL,BA,CAT,CVX,CSCO,KO,...,NKE,NVDA,PG,CRM,SHW,TRV,UNH,VZ,V,WMT
Date,,,,,,,,,,,,,,,,,,,,,
2019-01-02,122.66,86.63,152.61,76.96,37.47,314.65,108.02,79.87,34.47,37.58,...,66.56,3.37,75.35,133.24,122.22,100.20,215.45,36.96,126.07,27.91
2019-01-03,118.04,84.94,150.29,75.01,33.74,302.10,103.86,78.34,33.22,37.35,...,65.38,3.17,74.82,128.18,118.53,98.40,209.58,37.09,121.53,27.77
2019-01-04,122.90,88.76,155.43,78.77,35.18,317.82,109.54,79.97,34.71,38.10,...,67.09,3.37,76.35,135.61,121.67,101.32,212.03,37.18,126.76,27.94
2019-01-07,122.62,89.24,157.52,81.48,35.10,318.82,109.60,81.01,34.95,37.60,...,68.05,3.55,76.04,139.80,123.39,101.00,212.44,37.42,129.05,28.27
2019-01-08,123.13,89.68,159.54,82.83,35.77,330.89,110.92,80.65,35.23,38.02,...,68.96,3.46,76.32,143.24,124.26,100.60,215.28,38.51,129.75,28.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-04-23,144.09,318.55,346.01,255.08,273.18,234.15,835.24,185.90,88.59,76.28,...,44.38,199.41,144.62,172.85,336.79,306.05,354.56,47.22,308.24,131.78
2026-04-24,145.24,314.08,341.97,263.99,270.81,232.44,830.79,183.53,89.01,76.63,...,44.29,208.03,148.18,177.70,336.83,301.47,354.92,46.38,308.78,129.67
2026-04-27,145.02,318.84,337.63,261.12,267.36,231.33,828.79,183.10,88.26,75.44,...,44.74,216.36,148.40,179.72,335.23,302.48,354.69,47.10,309.01,127.35
2026-04-28,145.28,315.90,337.02,259.70,270.46,230.72,817.87,186.65,86.86,78.35,...,44.63,212.92,149.17,180.85,323.43,308.73,366.77,47.24,308.66,127.35
2026-04-29,143.13,315.65,335.49,263.04,269.92,224.11,810.05,190.48,89.57,78.87,...,44.00,209.01,146.46,180.75,317.03,300.99,370.74,46.61,334.17,127.77

In [10]:
# Calculate Annual Returns.
annual_returns = bb.annualized_returns(df, timeperiod='daily', years=1)
annual_returns

MMM      6.23
AXP     20.38
AMGN    23.15
AMZN    40.14
AAPL    29.13
BA      22.93
CAT    166.66
CVX     43.38
CSCO    61.21
KO      13.05
DIS     13.60
GS      69.17
HD      -7.27
HON     13.58
IBM     -1.45
JNJ     50.42
JPM     29.62
MCD     -6.32
MRK     38.21
MSFT     9.34
NKE    -20.60
NVDA    92.49
PG      -6.91
CRM    -31.27
SHW     -3.46
TRV     17.37
UNH     -9.24
VZ      17.36
V       -0.04
WMT     35.63
dtype: float64

In [11]:
# Calculate 3 month, 6 months, 1 year, 1-1 year, 3 year, and 5 year annualized returns.
annual_returns_3mo = bb.annualized_returns(df, timeperiod='daily', years=3/12)
annual_returns_6mo = bb.annualized_returns(df, timeperiod='daily', years=6/12)
annual_returns_1yr = bb.annualized_returns(df, timeperiod='daily', years=1)
annual_returns_1_1yr = bb.annualized_returns(df, timeperiod='daily', years=1, offset=1)
annual_returns_3yr = bb.annualized_returns(df, timeperiod='daily', years=3)
annual_returns_5yr = bb.annualized_returns(df, timeperiod='daily', years=5)

In [12]:
# Calculate 20 day annualized volatility.
daily_returns = df.pct_change()
years = bb.TRADING_DAYS_PER_MONTH / bb.TRADING_DAYS_PER_YEAR
vola = bb.annualized_standard_deviation(daily_returns, timeperiod='daily', years=years)

In [13]:
# Calculate 20 day annualized downside volatility.
ds_vola = bb.annualized_standard_deviation(daily_returns, timeperiod='daily', years=years, downside=True)

In [14]:
# Resample df on a monthly basis.
df.index = pd.to_datetime(df.index)
monthly = df.resample('ME').ffill()

In [15]:
# Calculate monthly returns.
monthly_returns = monthly.pct_change()

In [16]:
# Calculate 1 year, 3 year, and 5 year annualized standard deviation.
std_dev_1yr = bb.annualized_standard_deviation(monthly_returns, timeperiod='monthly', years=1)
std_dev_3yr = bb.annualized_standard_deviation(monthly_returns, timeperiod='monthly', years=3)
std_dev_5yr = bb.annualized_standard_deviation(monthly_returns, timeperiod='monthly', years=5)

In [17]:
# Read investment-options-header.csv
lines = []
with open('investment-options-in.csv', 'r') as f:
    lines = [line.strip() for line in f]

In [18]:
# For each symbol, write out the 1 Yr, 3 Yr, 5 Yr, and std dev.
out = lines.copy()

for i, (index, row) in enumerate(dow30.iterrows()):

    symbol = index
    description = row['Description']
    asset_class = row['Asset Class']

    ret_3mo = annual_returns_3mo[symbol]
    ret_6mo = annual_returns_6mo[symbol]
    ret_1yr = annual_returns_1yr[symbol]
    ret_1_1yr = annual_returns_1_1yr[symbol]
    ret_3yr = annual_returns_3yr[symbol]
    ret_5yr = annual_returns_5yr[symbol]
    
    if np.isnan(ret_3yr): ret_3yr = ret_1yr
    if np.isnan(ret_5yr): ret_5yr = ret_3yr

    _vola = vola[symbol]*100
    _ds_vola = ds_vola[symbol]*100
    sd_1yr = std_dev_1yr[symbol]*100
    sd_3yr = std_dev_3yr[symbol]*100
    sd_5yr = std_dev_5yr[symbol]*100

    out.append(
        f'"{symbol}","{description}","{asset_class}",'
        f'"{ret_3mo:0.2f}","{ret_6mo:0.2f}","{ret_1yr:0.2f}","{ret_1_1yr:0.2f}","{ret_3yr:0.2f}",'
        f'"{ret_5yr:0.2f}","{_vola:0.2f}","{_ds_vola:0.2f}","{sd_1yr:0.2f}","{sd_3yr:0.2f}","{sd_5yr:0.2f}"'
    )

In [19]:
# Write out asset-classes.csv
with open('investment-options.csv', 'w') as f:
    for line in out:
        f.write(line + '\n')